name: Node.js Docker CI/CD (Build & Push to GHCR)

# 1. TRIGGER (CI Phase Start)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # e.g., shershahkx/Gen_AI_Mid_Term

# Define the build and push job
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Continuous Integration (CI) Steps ---
      # Optional: Run Node.js Tests before building the Docker image
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match version from Dockerfile

      - name: Install dependencies and Run Tests (Optional but Recommended)
        run: |
          npm install
          # Replace 'npm test' with the actual command to run your project's tests
          # If your tests require a database or other services, this step will be more complex
          npm test 

      # --- Continuous Delivery (CD) Steps: Docker Build and Push ---

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=sha- # Unique tag per commit
            type=raw,value=latest,enable={{is_default_branch}} # 'latest' tag on main branch

      - name: Build and push Node.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}